### ISSUE TITLE
למצוא API לכתובות בישראל מול איזשהו משרד

### ISSUE THREAD

**Issue by Wahalez** [Wahalez/dddm#14]
למצוא API לכתובות בישראל מול איזשהו משרד
כתיבת פונקציה לשליפת הכתובות ( ערים, רחובות ).

**Comment by MasterChiefProject** [comment]
![image](https://github.com/Wahalez/dddm/assets/46121368/54f6914b-b90e-4321-861e-32d69c7a7137)

**Comment by Wahalez** [comment]
מה הפלט של זה ? תצרף. אם זה טוב, תכתוב פונקציה שנקרא לה בעליית האתר וכתיבה ל modal של זה.

**Comment by MasterChiefProject** [comment]
סבבה עידכנתי את הפלט, תסתכל דניאל 3: (פשוט תלחץ על הכפתור Fetch Data והפלט יהיה כל הערים במדינת ישראל
![image](https://github.com/Wahalez/dddm/assets/46121368/515e05b3-821e-4d95-b5fe-f4bfb81ad2c8)

**Comment by Wahalez** [comment]
זה נראה טוב כן. 
מה זה כפתור fetch data ? 
כתבת פונקציה לזה ? עשית push לorigin branch שלך ? 
1. לוודא כתיבת פונקציה
2. לכתוב את הרשימת ערים לתוך modal ( כלומר לשמור את הנתון בmodal משלו ).

**Comment by MasterChiefProject** [comment]
1. לחיצה על הכפתור fetch data מבצע את ההדפסה של כל הערים, הפונקציה נמצאת ב: dddm\frontend\api\address_api.js
2. לגבי modal, אני צריך ליצור שם קובץ מסוג ספציפי? ושם ספציפי? איך כאילו modal אמור להיראות? המערך של הערים יהיה שמור שם?

**Comment by Wahalez** [comment]
תפלטר לפי אנגלית, תכתוב את הנתונים לmodel.

**Comment by MasterChiefProject** [comment]
בוצע, שימוש בAPI של gov.co.il, שמירה בקובץ model.js את מערך הערים, פילטור לפי אנגלית יותר טוב בtextbox של הערים.

**Comment by Wahalez** [comment]
לא טוב. 
הAPI נקרא עדיין אחרי כל כתיבה של אות. ביקשתי להפריד את הנ"ל לפונקציה נפרדת שנקראת בעת עליית האתר פעם אחת. 
כמו כן, אם הנתונים נשמרים במודל, אין צורך להחזיר את הנתונים שהתקבלו מהAPI באמצעות response / request. 
וכמובן, שינוי שמות קבצים לאותיות קטנות ולא גדולות. 
בבקשה לתקן.

**Comment by MasterChiefProject** [comment]
עודכן
